# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: trusty
cache: packages
sudo: false

cache:
  packages: true

warnings_are_errors: true

#jdk:
#  - oraclejdk8

matrix:
  include:
    - name: "Spark 2.2.1 (R oldrel, oraclejdk8)"
      r: oldrel
      dist: xenial
      sudo: true
      env:
        - JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64/jre"
        - LD_LIBRARY_PATH="/usr/local/lib"
        - SPARK_VERSION="2.2.1"
        - JAVA_VERSION="openjdk8"
      addons:
        apt:
          packages:
            - openjdk-8-jre
    - name: "Spark 2.3.2 (R release, oraclejdk8)"
      r: release
      dist: xenial
      sudo: true
      env:
        - JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64/jre"
        - LD_LIBRARY_PATH="/usr/local/lib"
        - SPARK_VERSION="2.3.2"
        - JAVA_VERSION="openjdk8"
      addons:
        apt:
          packages:
            - openjdk-8-jre
    - name: "Spark 2.4.0 (R release, oraclejdk8)"
      r: release
      dist: xenial
      sudo: true
      env:
        - JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64/jre"
        - LD_LIBRARY_PATH="/usr/local/lib"
        - SPARK_VERSION="2.4.0"
        - JAVA_VERSION="openjdk8"
      addons:
        apt:
          packages:
            - openjdk-8-jre
