# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: xenial
cache: packages
sudo: true

cache:
  packages: true

warnings_are_errors: true

matrix:
  include:
    - name: "Spark 2.4.0 (R release, oraclejdk8)"
      r: release
      env:
        - JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64/jre"
        - LD_LIBRARY_PATH="/usr/local/lib"
        - SPARK_VERSION="2.4.0"
        - JAVA_VERSION="openjdk8"
      addons:
        apt:
          packages:
            - openjdk-8-jre
